import type { UiLang } from "./i18n";

/**
 * Discovery categories for the nearby filter panel. Shop `category` is free
 * text written by the model in whatever language the owner spoke, so each
 * category carries match terms across all three scripts and is tested against
 * the shop's category + name + products text (case-insensitive substring).
 */
export interface ShopCategory {
  id: string;
  labels: Record<UiLang, string>;
  match: string[];
}

export const SHOP_CATEGORIES: ShopCategory[] = [
  {
    id: "grocery",
    labels: { en: "Grocery / Kirana", hi: "किराना", pa: "ਕਰਿਆਨਾ" },
    match: [
      "grocery",
      "kirana",
      "general store",
      "ration",
      "किराना",
      "जनरल",
      "राशन",
      "ਕਰਿਆਨਾ",
      "ਜਨਰਲ",
      "ਰਾਸ਼ਨ",
    ],
  },
  {
    id: "dairy",
    labels: { en: "Dairy", hi: "डेयरी", pa: "ਡੇਅਰੀ" },
    match: [
      "dairy",
      "milk",
      "paneer",
      "डेयरी",
      "दूध",
      "पनीर",
      "ਡੇਅਰੀ",
      "ਦੁੱਧ",
      "ਪਨੀਰ",
    ],
  },
  {
    id: "fruits-veg",
    labels: { en: "Fruits & vegetables", hi: "फल-सब्ज़ी", pa: "ਫਲ-ਸਬਜ਼ੀ" },
    match: [
      "vegetable",
      "fruit",
      "sabzi",
      "सब्जी",
      "सब्ज़ी",
      "फल",
      "ਸਬਜ਼ੀ",
      "ਫਲ",
    ],
  },
  {
    id: "sweets-bakery",
    labels: { en: "Sweets & bakery", hi: "मिठाई-बेकरी", pa: "ਮਿਠਾਈ-ਬੇਕਰੀ" },
    match: [
      "sweet",
      "bakery",
      "cake",
      "mithai",
      "मिठाई",
      "बेकरी",
      "केक",
      "ਮਿਠਾਈ",
      "ਬੇਕਰੀ",
      "ਕੇਕ",
    ],
  },
  {
    id: "restaurant",
    labels: { en: "Restaurant / Food", hi: "रेस्टोरेंट-खाना", pa: "ਰੈਸਟੋਰੈਂਟ-ਖਾਣਾ" },
    match: [
      "restaurant",
      "dhaba",
      "cafe",
      "food",
      "tiffin",
      "रेस्टोरेंट",
      "ढाबा",
      "कैफ़े",
      "खाना",
      "टिफिन",
      "ਰੈਸਟੋਰੈਂਟ",
      "ਢਾਬਾ",
      "ਕੈਫੇ",
      "ਖਾਣਾ",
    ],
  },
  {
    id: "meat-fish",
    labels: { en: "Meat & fish", hi: "मीट-मछली", pa: "ਮੀਟ-ਮੱਛੀ" },
    match: [
      "meat",
      "chicken",
      "mutton",
      "fish",
      "egg",
      "मीट",
      "चिकन",
      "मटन",
      "मछली",
      "अंड",
      "ਮੀਟ",
      "ਚਿਕਨ",
      "ਮਟਨ",
      "ਮੱਛੀ",
      "ਆਂਡ",
    ],
  },
  {
    id: "mobile",
    labels: { en: "Mobile & recharge", hi: "मोबाइल-रिचार्ज", pa: "ਮੋਬਾਈਲ-ਰੀਚਾਰਜ" },
    match: [
      "mobile",
      "phone",
      "recharge",
      "sim",
      "मोबाइल",
      "फ़ोन",
      "फोन",
      "रिचार्ज",
      "ਮੋਬਾਈਲ",
      "ਫ਼ੋਨ",
      "ਫੋਨ",
      "ਰੀਚਾਰਜ",
    ],
  },
  {
    id: "electronics",
    labels: { en: "Electronics", hi: "इलेक्ट्रॉनिक्स", pa: "ਇਲੈਕਟ੍ਰਾਨਿਕਸ" },
    match: [
      "electronic",
      "appliance",
      "tv",
      "fridge",
      "cooler",
      "इलेक्ट",
      "टीवी",
      "फ्रिज",
      "कूलर",
      "ਇਲੈਕਟ",
      "ਟੀਵੀ",
      "ਫਰਿੱਜ",
      "ਕੂਲਰ",
    ],
  },
  {
    id: "repair",
    labels: { en: "Repair & services", hi: "रिपेयर-सर्विस", pa: "ਰਿਪੇਅਰ-ਸਰਵਿਸ" },
    match: [
      "repair",
      "service",
      "रिपेयर",
      "मरम्मत",
      "सर्विस",
      "ਰਿਪੇਅਰ",
      "ਮੁਰੰਮਤ",
      "ਸਰਵਿਸ",
    ],
  },
  {
    id: "auto",
    labels: { en: "Auto & garage", hi: "ऑटो-गैराज", pa: "ਆਟੋ-ਗੈਰਾਜ" },
    match: [
      "garage",
      "auto",
      "tyre",
      "puncture",
      "mechanic",
      "गैराज",
      "टायर",
      "पंचर",
      "मैकेनिक",
      "ਗੈਰਾਜ",
      "ਟਾਇਰ",
      "ਪੰਕਚਰ",
      "ਮਕੈਨਿਕ",
    ],
  },
  {
    id: "clothing",
    labels: { en: "Clothing & boutique", hi: "कपड़े-बुटीक", pa: "ਕੱਪੜੇ-ਬੁਟੀਕ" },
    match: [
      "cloth",
      "garment",
      "boutique",
      "saree",
      "kurta",
      "कपड़",
      "बुटीक",
      "साड़ी",
      "कुर्ता",
      "ਕੱਪੜ",
      "ਬੁਟੀਕ",
      "ਸਾੜ੍ਹੀ",
      "ਕੁੜਤਾ",
    ],
  },
  {
    id: "tailor",
    labels: { en: "Tailor", hi: "दर्ज़ी", pa: "ਦਰਜ਼ੀ" },
    match: ["tailor", "stitch", "दर्जी", "दर्ज़ी", "सिलाई", "ਦਰਜ਼ੀ", "ਸਿਲਾਈ"],
  },
  {
    id: "footwear",
    labels: { en: "Footwear", hi: "जूते-चप्पल", pa: "ਜੁੱਤੇ-ਚੱਪਲ" },
    match: ["shoe", "footwear", "chappal", "जूत", "चप्पल", "ਜੁੱਤ", "ਚੱਪਲ"],
  },
  {
    id: "jewellery",
    labels: { en: "Jewellery", hi: "ज्वेलरी-सुनार", pa: "ਗਹਿਣੇ-ਸੁਨਿਆਰ" },
    match: [
      "jewel",
      "gold",
      "silver",
      "ज्वेलरी",
      "सुनार",
      "सोना",
      "चांदी",
      "गहन",
      "ਗਹਿਣ",
      "ਸੁਨਿਆਰ",
      "ਸੋਨਾ",
      "ਚਾਂਦੀ",
    ],
  },
  {
    id: "salon",
    labels: { en: "Salon & beauty", hi: "सैलून-ब्यूटी", pa: "ਸੈਲੂਨ-ਬਿਊਟੀ" },
    match: [
      "salon",
      "saloon",
      "barber",
      "parlour",
      "parlor",
      "beauty",
      "सैलून",
      "नाई",
      "पार्लर",
      "ब्यूटी",
      "ਸੈਲੂਨ",
      "ਨਾਈ",
      "ਪਾਰਲਰ",
      "ਬਿਊਟੀ",
    ],
  },
  {
    id: "clinic",
    labels: { en: "Clinic & pharmacy", hi: "क्लिनिक-दवा", pa: "ਕਲੀਨਿਕ-ਦਵਾਈ" },
    match: [
      "clinic",
      "doctor",
      "medical",
      "pharmacy",
      "chemist",
      "hospital",
      "क्लिनिक",
      "डॉक्टर",
      "दवा",
      "मेडिकल",
      "अस्पताल",
      "ਕਲੀਨਿਕ",
      "ਡਾਕਟਰ",
      "ਦਵਾਈ",
      "ਮੈਡੀਕਲ",
      "ਹਸਪਤਾਲ",
    ],
  },
  {
    id: "optician",
    labels: { en: "Optician", hi: "चश्मे", pa: "ਐਨਕਾਂ" },
    match: ["optical", "optician", "chashma", "चश्मा", "ऑप्टिकल", "ਐਨਕ", "ਆਪਟੀਕਲ"],
  },
  {
    id: "tuition",
    labels: { en: "Tuition & coaching", hi: "ट्यूशन-कोचिंग", pa: "ਟਿਊਸ਼ਨ-ਕੋਚਿੰਗ" },
    match: [
      "tuition",
      "coaching",
      "classes",
      "academy",
      "ट्यूशन",
      "कोचिंग",
      "क्लास",
      "अकादमी",
      "ਟਿਊਸ਼ਨ",
      "ਕੋਚਿੰਗ",
      "ਕਲਾਸ",
      "ਅਕੈਡਮੀ",
    ],
  },
  {
    id: "stationery",
    labels: { en: "Stationery & printing", hi: "स्टेशनरी-प्रिंट", pa: "ਸਟੇਸ਼ਨਰੀ-ਪ੍ਰਿੰਟ" },
    match: [
      "stationery",
      "book",
      "xerox",
      "print",
      "स्टेशनरी",
      "किताब",
      "ज़ेरॉक्स",
      "प्रिंट",
      "ਸਟੇਸ਼ਨਰੀ",
      "ਕਿਤਾਬ",
      "ਪ੍ਰਿੰਟ",
    ],
  },
  {
    id: "hardware",
    labels: { en: "Hardware & paint", hi: "हार्डवेयर-पेंट", pa: "ਹਾਰਡਵੇਅਰ-ਪੇਂਟ" },
    match: [
      "hardware",
      "paint",
      "sanitary",
      "हार्डवेयर",
      "पेंट",
      "सैनिटरी",
      "ਹਾਰਡਵੇਅਰ",
      "ਪੇਂਟ",
      "ਸੈਨੇਟਰੀ",
    ],
  },
  {
    id: "furniture",
    labels: { en: "Furniture", hi: "फर्नीचर", pa: "ਫਰਨੀਚਰ" },
    match: [
      "furniture",
      "sofa",
      "फर्नीचर",
      "सोफा",
      "लकड़ी",
      "ਫਰਨੀਚਰ",
      "ਸੋਫਾ",
      "ਲੱਕੜ",
    ],
  },
  {
    id: "flowers-gifts",
    labels: { en: "Flowers & gifts", hi: "फूल-गिफ्ट", pa: "ਫੁੱਲ-ਗਿਫਟ" },
    match: [
      "flower",
      "gift",
      "फूल",
      "गिफ्ट",
      "उपहार",
      "ਫੁੱਲ",
      "ਗਿਫਟ",
      "ਤੋਹਫ਼",
    ],
  },
];

export function matchesCategory(cat: ShopCategory, haystack: string): boolean {
  const h = haystack.toLowerCase();
  return cat.match.some((term) => h.includes(term));
}
